[package]
name = "cyrkensia"
version = "1.2.0"
edition = "2021"
license = "EUPL-1.2"

[dependencies]


[[bin]]
name = "cyrkensia"
path = "src/bin/cyrkensia.rs"
required-features = []

[[bin]]
name = "cyrkensia-cfg"
path = "src/bin/cyrkensia-cfg.rs"
required-features = []