install:
	@cd src; go install cyrkensia.go

windows:
	@cd src; go build -o ../build/cyrkensia.exe cyrkensia.go

linux:
	@cd src; go build -o ../build/cyrkensia cyrkensia.go

run:
	@cd src; go run cyrkensia.go

help:
	@cd src; go run cyrkensia.go -h
