install:
	go install cyrkensia.go

windows:
	go build -o ../build/cyrkensia.exe cyrkensia.go

linux:
	go build -o ../build/cyrkensia cyrkensia.go

run:
	go run cyrkensia.go

help:
	go run cyrkensia.go -h
